#!/usr/bin/env python3
"""Generate the Flutter theme of a flutter-app-structure app from a theme spec.

Reads design/theme.spec.json (see references/spec-format.md), validates it and
writes ONLY these files (all marked GENERATED):

  lib/shared/theme/tokens/app_colors.dart          _Palette → AppColorsLight/Dark → AppColorExtension
  lib/shared/theme/tokens/app_typography.dart      all 15 Material text roles + extra styles
  lib/shared/theme/tokens/app_text_extension.dart  context.appText.<extra>
  lib/shared/theme/tokens/app_dimensions.dart      spacing / radius / sizes (shell contract + extras)
  lib/shared/theme/component_themes/color_schemes.dart   ColorScheme.fromSeed + provided roles
  lib/shared/theme/component_themes/button_themes.dart
  lib/shared/theme/component_themes/input_decoration_theme.dart
  lib/shared/theme/component_themes/surface_themes.dart  card, chip, divider, bottom sheet
  lib/shared/theme/app_theme.dart, theme_context_ext.dart, theme.dart
  lib/shared/theme/preview/theme_preview_screen.dart     debug preview of every token
  test/shared/theme/{app_theme,theme_contrast,theme_preview_screen}_test.dart
  design/THEME_REPORT.md                                 mapping report for designer sign-off

Usage:
  python3 generate_theme.py --root . [--spec design/theme.spec.json] [--allow-open-conflicts] [--dry-run]
"""

import argparse
import datetime
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import theme_spec as ts  # noqa: E402

HEADER = ("// GENERATED by the flutter-design-system-theme skill from design/theme.spec.json.\n"
          "// Do not edit by hand: change the spec and re-run scripts/generate_theme.py.\n")


# ---------------------------------------------------------------- helpers


def camel(text):
    words = re.findall(r"[A-Za-z0-9]+", text)
    if not words:
        return "color"
    out = words[0][0].lower() + words[0][1:] + "".join(w[0].upper() + w[1:] for w in words[1:])
    return out if out[0].isalpha() else "c" + out


def num(v):
    if isinstance(v, float):
        v = round(v, 4)
    if isinstance(v, float) and v.is_integer():
        v = int(v)
    return repr(v) if isinstance(v, float) else str(v)


def src(entry):
    if not isinstance(entry, dict):
        return ""
    s = entry.get("source", "")
    return f"  // {s}" if s else ""


def read_package(root):
    m = re.search(r"^name:\s*([A-Za-z0-9_]+)", (root / "pubspec.yaml").read_text(), re.M)
    if not m:
        sys.exit("Could not read `name:` from pubspec.yaml")
    return m.group(1)


class Palette:
    """Deduplicates raw colours and gives each a readable private name."""

    def __init__(self):
        self.by_value, self.names = {}, {}

    def add(self, entry, fallback):
        value = entry["value"].upper()
        if value in self.by_value:
            return self.by_value[value]
        base = camel(entry.get("name") or entry.get("token") or fallback)
        name, i = base, 2
        while name in self.names:
            name, i = f"{base}{i}", i + 1
        self.by_value[value], self.names[name] = name, (value, entry)
        return name

    def dart(self):
        lines = []
        for name, (value, entry) in self.names.items():
            if isinstance(entry, dict) and entry.get("source"):
                lines.append(f"  // {entry['source']}")
            lines.append(f"  static const {name} = Color({ts.argb_literal(value)});")
        return "\n".join(lines)


def border_ref(ref, width=None):
    """BorderSide expression for an input border; 'none' draws no border."""
    return "BorderSide.none" if ref == "none" else None


def color_ref(ref, colors_var="colors", ext_var="appColors"):
    return f"{ext_var}.{ref[4:]}" if ref.startswith("ext.") else f"{colors_var}.{ref}"


def dim_ref(value, group, dims, prefer=None):
    """Use an AppDimensions constant when one has exactly this value."""
    if prefer and dims[group].get(prefer) == value:
        return f"AppDimensions.{prefer}"
    matches = [k for k, v in dims[group].items() if v == value]
    return f"AppDimensions.{matches[0]}" if len(matches) == 1 else num(value)


def shape_expr(radius, dims):
    if radius is None:
        return None
    if radius >= 9999:
        return "const StadiumBorder()"
    return f"RoundedRectangleBorder(borderRadius: BorderRadius.circular({dim_ref(radius, 'radius', dims)}))"


# ---------------------------------------------------------------- colours


def gen_colors(spec, palette):
    light, dark = ts.mode_colors(spec, "light"), ts.mode_colors(spec, "dark")
    ext = ts.extension_colors(spec)
    seed = spec.get("seed")

    light_lines = []
    if seed:
        light_lines.append(f"  static const seed = _Palette.{palette.add(seed, 'seed')};")
    else:
        light_lines.append("  static const seed = primary;")
    for role in ts.COLOR_ROLES:
        if role in light:
            light_lines.append(f"  static const {role} = _Palette.{palette.add(light[role], role)};")
    ext_light = []
    for name, entry in ext.items():
        ext_light.append(f"  static const {name} = _Palette.{palette.add(entry['light'], name)};")

    dark_lines = []
    for role in ts.COLOR_ROLES:
        if role in dark:
            dark_lines.append(f"  static const {role} = _Palette.{palette.add(dark[role], role + 'Dark')};")
    for name, entry in ext.items():
        if entry.get("dark"):
            dark_lines.append(f"  static const {name} = _Palette.{palette.add(entry['dark'], name + 'Dark')};")

    all_dark_ext = all(e.get("dark") for e in ext.values())
    fields = "\n".join(f"  final Color {n};" for n in ext)
    ctor = "\n".join(f"    required this.{n}," for n in ext)
    light_args = "\n".join(f"    {n}: AppColorsLight.{n}," for n in ext)
    derive_role = {"text": "text", "largeText": "text", "icon": "text", "border": "border", "fill": "fill"}
    dark_args = "\n".join(
        f"    {n}: AppColorsDark.{n}," if e.get("dark")
        else f"    {n}: _deriveDark(AppColorsLight.{n}, _DarkUsage.{derive_role[e.get('usage', 'text')]}),"
        for n, e in ext.items())
    copy_params = ", ".join(f"Color? {n}" for n in ext)
    copy_body = "\n".join(f"    {n}: {n} ?? this.{n}," for n in ext)
    lerp_body = "\n".join(f"      {n}: Color.lerp({n}, other.{n}, t)!," for n in ext)
    derive_fn = "" if all_dark_ext else '''
enum _DarkUsage { text, border, fill }

/// Dark-mode counterpart of a brand colour the design system only gave for
/// light mode, from Material's tonal palette of that colour: foregrounds
/// (text, icons) take the light dark-scheme tone, borders the subtle outline
/// tone, fills the container tone. Listed as "derived" in THEME_REPORT.md —
/// review it in the preview screen.
Color _deriveDark(Color light, _DarkUsage usage) {
  final scheme = ColorScheme.fromSeed(
    seedColor: light,
    brightness: Brightness.dark,
    dynamicSchemeVariant: DynamicSchemeVariant.fidelity,
  );
  return switch (usage) {
    _DarkUsage.text => scheme.primary,
    _DarkUsage.border => scheme.outlineVariant,
    _DarkUsage.fill => scheme.primaryContainer,
  };
}
'''
    dark_class = ("abstract final class AppColorsDark {\n" + "\n".join(dark_lines) + "\n}\n") if dark_lines else \
        "// No dark colours in the design system: the dark ColorScheme is derived from\n// AppColorsLight.seed (see color_schemes.dart).\n"

    return f"""{HEADER}
import 'package:flutter/material.dart';

// Layer 1: raw palette — private. Names come from the design system's tokens.
abstract final class _Palette {{
{palette.dart()}
}}

// Layer 2: semantic tokens. Only component_themes/ and AppColorExtension read
// these; widgets use `context.colors` / `context.appColors` so they stay
// correct in light and dark mode.
abstract final class AppColorsLight {{
{chr(10).join(light_lines)}

  // --- Brand colours Material's ColorScheme has no slot for ---
{chr(10).join(ext_light)}
}}

{dark_class}
/// Semantic colours Material's ColorScheme has no slot for.
/// Read with `context.appColors.<name>`.
@immutable
class AppColorExtension extends ThemeExtension<AppColorExtension> {{
  const AppColorExtension({{
{ctor}
  }});

  static const light = AppColorExtension(
{light_args}
  );

  static {'const' if all_dark_ext else 'final'} dark = AppColorExtension(
{dark_args}
  );

{fields}

  @override
  AppColorExtension copyWith({{{copy_params}}}) => AppColorExtension(
{copy_body}
  );

  @override
  AppColorExtension lerp(AppColorExtension? other, double t) {{
    if (other == null) return this;
    return AppColorExtension(
{lerp_body}
    );
  }}
}}
{derive_fn}"""


def gen_color_schemes(spec):
    variant = (spec.get("policy") or {}).get("schemeVariant", "fidelity")
    light, dark = ts.mode_colors(spec, "light"), ts.mode_colors(spec, "dark")

    def scheme(name, mode, roles, cls):
        overrides = "\n".join(f"  {r}: {cls}.{r}," for r in ts.COLOR_ROLES if r in roles)
        brightness = "  brightness: Brightness.dark,\n" if mode == "dark" else ""
        return (f"final {name} = ColorScheme.fromSeed(\n"
                f"  seedColor: AppColorsLight.seed,\n{brightness}"
                f"  dynamicSchemeVariant: DynamicSchemeVariant.{variant},\n{overrides}\n);\n")

    return f"""{HEADER}
import 'package:flutter/material.dart';

import '../tokens/app_colors.dart';

// Every role the design system provides is used exactly; every other role is
// derived from the seed by Material's tonal algorithm (see THEME_REPORT.md).

{scheme('lightColorScheme', 'light', light, 'AppColorsLight')}
{scheme('darkColorScheme', 'dark', dark, 'AppColorsDark')}"""


# ---------------------------------------------------------------- typography


def text_style_expr(style):
    parts = ["fontFamily: fontFamily", "fontFamilyFallback: fontFamilyFallback",
             f"fontSize: {num(style['fontSize'])}",
             f"fontWeight: FontWeight.w{style.get('fontWeight', 400)}"]
    if style.get("lineHeight"):
        parts.append(f"height: {num(style['lineHeight'])} / {num(style['fontSize'])}")
    ls = style.get("letterSpacing", 0)
    if ls:
        parts.append(f"letterSpacing: {num(ls)}")
    features = style.get("fontFeatures") or []
    if features:
        parts.append("fontFeatures: [" + ", ".join(f"FontFeature('{f}')" for f in features) + "]")
    return "TextStyle(\n    " + ",\n    ".join(parts) + ",\n  )"


def gen_typography(spec):
    typo = spec.get("typography") or {}
    roles, extras = typo.get("roles") or {}, typo.get("extras") or {}
    family = (typo.get("fontFamily") or {}).get("value")
    fallback = typo.get("fontFamilyFallback") or []
    lines = [
        f"  static const fontFamily = {repr(family)};" if family else "  static const String? fontFamily = null;",
        ("  static const fontFamilyFallback = [" + ", ".join(repr(f) for f in fallback) + "];")
        if fallback else "  static const List<String>? fontFamilyFallback = null;",
        "",
        "  // --- Material TextTheme roles (read via context.textTheme.<role>) ---",
    ]
    for role in ts.TYPE_ROLES:
        if role in roles:
            style = roles[role]
            lines.append(f"  /// {style.get('token', role)} — {style.get('source', '')}")
        else:
            size, line, weight, ls = ts.MATERIAL_TYPE_SCALE[role]
            style = {"fontSize": size, "lineHeight": line, "fontWeight": weight, "letterSpacing": ls}
            lines.append("  /// Material 3 default (not in the design system).")
        lines.append(f"  static const {role} = {text_style_expr(style)};")
        lines.append("")
    if extras:
        lines.append("  // --- Extra styles (read via context.appText.<name>) ---")
        for name, style in extras.items():
            lines.append(f"  /// {style.get('token', name)} — {style.get('source', '')}")
            lines.append(f"  static const {name} = {text_style_expr(style)};")
            lines.append("")
    theme_args = "\n".join(f"    {r}: {r}," for r in ts.TYPE_ROLES)
    return f"""{HEADER}
import 'package:flutter/material.dart';

/// Size, weight, line height and tracking only — colour comes from the theme.
abstract final class AppTypography {{
{chr(10).join(lines)}
  static const textTheme = TextTheme(
{theme_args}
  );
}}
"""


def gen_text_extension(spec):
    extras = list(((spec.get("typography") or {}).get("extras") or {}).keys())
    if not extras:
        return f"""{HEADER}
import 'package:flutter/material.dart';

/// Extra text styles beyond Material's TextTheme. The design system defines
/// none; add them under typography.extras in the spec.
@immutable
class AppTextExtension extends ThemeExtension<AppTextExtension> {{
  const AppTextExtension();

  factory AppTextExtension.withColor(Color color) => const AppTextExtension();

  @override
  AppTextExtension copyWith() => this;

  @override
  AppTextExtension lerp(AppTextExtension? other, double t) => this;
}}
"""
    ctor = "\n".join(f"    required this.{n}," for n in extras)
    with_color = "\n".join(f"    {n}: AppTypography.{n}.copyWith(color: color)," for n in extras)
    fields = "\n".join(f"  final TextStyle {n};" for n in extras)
    copy_params = ", ".join(f"TextStyle? {n}" for n in extras)
    copy_body = "\n".join(f"    {n}: {n} ?? this.{n}," for n in extras)
    lerp_body = "\n".join(f"      {n}: TextStyle.lerp({n}, other.{n}, t)!," for n in extras)
    return f"""{HEADER}
import 'package:flutter/material.dart';

import 'app_typography.dart';

/// Extra text styles beyond Material's TextTheme, coloured by the theme.
/// Read with `context.appText.<name>`.
@immutable
class AppTextExtension extends ThemeExtension<AppTextExtension> {{
  const AppTextExtension({{
{ctor}
  }});

  factory AppTextExtension.withColor(Color color) => AppTextExtension(
{with_color}
  );

{fields}

  @override
  AppTextExtension copyWith({{{copy_params}}}) => AppTextExtension(
{copy_body}
  );

  @override
  AppTextExtension lerp(AppTextExtension? other, double t) {{
    if (other == null) return this;
    return AppTextExtension(
{lerp_body}
    );
  }}
}}
"""


# ---------------------------------------------------------------- dimensions


def resolve_dims(spec):
    dims, provenance = {}, {}
    for group, contract in (("spacing", ts.CONTRACT_SPACING), ("radius", ts.CONTRACT_RADIUS),
                            ("sizes", ts.CONTRACT_SIZES)):
        values = spec.get(group) or {}
        dims[group] = {}
        for key, default in contract.items():
            if key in values:
                dims[group][key] = values[key]["value"]
                provenance[key] = values[key].get("source", "")
            else:
                dims[group][key] = default
                provenance[key] = "shell default (not in the design system)"
        for key, entry in values.items():
            if key not in contract:
                dims[group][key] = entry["value"]
                provenance[key] = entry.get("source", "")
    return dims, provenance


def gen_dimensions(dims, provenance):
    lines = []
    for group, title in (("spacing", "Spacing"), ("radius", "Radius"), ("sizes", "Component sizes")):
        lines.append(f"  // --- {title} ---")
        for key, value in dims[group].items():
            v = float(value)
            lines.append(f"  static const {key} = {num(v) if not v.is_integer() else f'{int(v)}.0'};  // {provenance[key]}")
        lines.append("")
    return f"""{HEADER}
/// Spacing, radius and size tokens. Widgets never use raw numbers for padding,
/// gaps or radii. The shell's contract names are always present.
abstract final class AppDimensions {{
{chr(10).join(lines).rstrip()}
}}
"""


# ---------------------------------------------------------------- component themes


def gen_button_themes(spec, dims):
    comp = spec.get("components") or {}
    f, o, t = comp.get("filledButton") or {}, comp.get("outlinedButton") or {}, comp.get("textButton") or {}

    def text_style(c, default="labelLarge"):
        return f"AppTypography.{c.get('textStyle', default)}"

    def height(c):
        return dim_ref(c.get("height", dims["sizes"]["buttonHeight"]), "sizes", dims, prefer="buttonHeight")

    fshape = shape_expr(f.get("radius", 9999), dims)
    fbg = color_ref(f.get("background", "primary"))
    ffg = color_ref(f.get("foreground", "onPrimary"))
    pressed = ""
    if f.get("pressedBackground"):
        pressed = f"""
  ).copyWith(
    backgroundColor: WidgetStateProperty.resolveWith((states) {{
      if (states.contains(WidgetState.disabled)) {{
        return colors.onSurface.withValues(alpha: 0.12);
      }}
      if (states.contains(WidgetState.pressed)) {{
        return {color_ref(f['pressedBackground'])};
      }}
      return {fbg};
    }}),
    overlayColor: const WidgetStatePropertyAll(Colors.transparent),"""

    o = {**{k: f[k] for k in ("radius", "height", "textStyle") if k in f}, **o}  # outlined inherits filled
    oshape = shape_expr(o.get("radius", 9999), dims)
    oside = f"BorderSide(color: {color_ref(o.get('border', 'outline'))}, width: {num(o.get('borderWidth', 1))})"
    obg = f"\n    backgroundColor: {color_ref(o['background'])}," if o.get("background") else ""
    tpad = ""
    if t.get("horizontalPadding") is not None:
        tpad = f"\n    padding: const EdgeInsets.symmetric(horizontal: {num(t['horizontalPadding'])}),"

    return f"""{HEADER}
import 'package:flutter/material.dart';

import '../tokens/app_colors.dart';
import '../tokens/app_dimensions.dart';
import '../tokens/app_typography.dart';

FilledButtonThemeData filledButtonTheme(
  ColorScheme colors,
  AppColorExtension appColors,
) => FilledButtonThemeData(
  style: FilledButton.styleFrom(
    backgroundColor: {fbg},
    foregroundColor: {ffg},
    minimumSize: const Size.fromHeight({height(f)}),
    shape: {fshape},
    textStyle: {text_style(f)},{pressed}
  ),
);

OutlinedButtonThemeData outlinedButtonTheme(
  ColorScheme colors,
  AppColorExtension appColors,
) => OutlinedButtonThemeData(
  style: OutlinedButton.styleFrom(
    foregroundColor: {color_ref(o.get('foreground', 'onSurface'))},{obg}
    side: {oside},
    minimumSize: const Size.fromHeight({height(o)}),
    shape: {oshape},
    textStyle: {text_style(o)},
  ),
);

TextButtonThemeData textButtonTheme(
  ColorScheme colors,
  AppColorExtension appColors,
) => TextButtonThemeData(
  style: TextButton.styleFrom(
    foregroundColor: {color_ref(t.get('foreground', 'primary'))},
    textStyle: {text_style(t)},{tpad}
  ),
);
"""


def gen_input_theme(spec, dims):
    i = (spec.get("components") or {}).get("input") or {}
    radius = dim_ref(i.get("radius", dims["radius"]["radiusMd"]), "radius", dims)
    height = dim_ref(i.get("height", dims["sizes"]["inputHeight"]), "sizes", dims, prefer="inputHeight")
    focus_w = num(i.get("focusBorderWidth", 2))
    no_border = ("OutlineInputBorder(borderRadius: BorderRadius.circular("
                 + radius + "), borderSide: BorderSide.none)") if i.get("border") == "none" else ""
    return f"""{HEADER}
import 'package:flutter/material.dart';

import '../tokens/app_colors.dart';
import '../tokens/app_dimensions.dart';

InputDecorationTheme inputDecorationTheme(
  ColorScheme colors,
  AppColorExtension appColors,
) {{
  OutlineInputBorder border(Color color, [double width = 1]) =>
      OutlineInputBorder(
        borderRadius: BorderRadius.circular({radius}),
        borderSide: BorderSide(color: color, width: width),
      );

  return InputDecorationTheme(
    filled: true,
    fillColor: {color_ref(i.get('fill', 'surfaceContainer'))},
    constraints: const BoxConstraints(minHeight: {height}),
    contentPadding: const EdgeInsets.symmetric(
      horizontal: {num(i.get('paddingHorizontal', 16))},
      vertical: {num(i.get('paddingVertical', 12))},
    ),
    border: {no_border if i.get('border') == 'none' else "border(" + color_ref(i.get('border', 'outline')) + ")"},
    enabledBorder: {no_border if i.get('border') == 'none' else "border(" + color_ref(i.get('border', 'outline')) + ")"},
    focusedBorder: border({color_ref(i.get('focusBorder', 'primary'))}, {focus_w}),
    errorBorder: border({color_ref(i.get('errorBorder', 'error'))}),
    focusedErrorBorder: border({color_ref(i.get('errorBorder', 'error'))}, {focus_w}),
  );
}}
"""


# Public names each token file defines (keep in sync with gen_colors / gen_typography / gen_dimensions).
TOKEN_IMPORTS = {"app_dimensions": ("AppDimensions",), "app_typography": ("AppTypography",),
                 "app_colors": ("AppColorExtension", "AppColorsLight")}


def prune_token_imports(text):
    """Drop `../tokens/<x>.dart` imports whose names the file doesn't use (a design with only literal radii…)."""
    for module, symbols in TOKEN_IMPORTS.items():
        line = f"import '../tokens/{module}.dart';\n"
        body = text.replace(line, "")
        if line in text and not any(re.search(rf"\b{sym}\b", body) for sym in symbols):
            text = body
    return re.sub(r"\n{3,}", "\n\n", text)


def gen_surface_themes(spec, dims):
    comp = spec.get("components") or {}
    card, chip = comp.get("card") or {}, comp.get("chip") or {}
    div, sheet = comp.get("divider") or {}, comp.get("bottomSheet") or {}

    card_radius = dim_ref(card.get("radius", dims["radius"]["radiusMd"]), "radius", dims)
    card_side = f", side: BorderSide(color: {color_ref(card['border'])})" if card.get("border") else ""
    card_color = f"\n  color: {color_ref(card['color'])}," if card.get("color") else ""

    chip_radius = dim_ref(chip.get("radius", dims["radius"]["radiusSm"]), "radius", dims)
    chip_bg = f"\n  backgroundColor: {color_ref(chip['background'])}," if chip.get("background") else ""
    chip_side = f"\n  side: BorderSide(color: {color_ref(chip['border'])})," if chip.get("border") else ""
    chip_label = ""
    if chip.get("textStyle") or chip.get("label"):
        base = f"AppTypography.{chip.get('textStyle', 'labelLarge')}"
        chip_label = (f"\n  labelStyle: {base}.copyWith(color: {color_ref(chip['label'])}),"
                      if chip.get("label") else f"\n  labelStyle: {base},")

    sheet_bg = color_ref(sheet.get("background", "surfaceContainerLow"))
    sheet_radius = dim_ref(sheet.get("topRadius", dims["radius"]["radiusXl"]), "radius", dims)
    barrier = color_ref(sheet.get("barrierColor", "scrim"))
    opacity = num(sheet.get("barrierOpacity", 0.32))

    typo_import = "import '../tokens/app_typography.dart';\n" if chip_label else ""
    return f"""{HEADER}
import 'package:flutter/material.dart';

import '../tokens/app_colors.dart';
import '../tokens/app_dimensions.dart';
{typo_import}
CardThemeData cardTheme(ColorScheme colors, AppColorExtension appColors) =>
    CardThemeData({card_color}
      elevation: {num(card.get('elevation', 0))},
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular({card_radius}){card_side},
      ),
    );

ChipThemeData chipTheme(ColorScheme colors, AppColorExtension appColors) =>
    ChipThemeData({chip_bg}{chip_side}{chip_label}
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular({chip_radius}),
      ),
    );

DividerThemeData dividerTheme(
  ColorScheme colors,
  AppColorExtension appColors,
) => DividerThemeData(
  color: {color_ref(div.get('color', 'outlineVariant'))},
  thickness: {num(div.get('thickness', 1))},
);

BottomSheetThemeData bottomSheetTheme(
  ColorScheme colors,
  AppColorExtension appColors,
) => BottomSheetThemeData(
  backgroundColor: {sheet_bg},
  modalBackgroundColor: {sheet_bg},
  modalBarrierColor: {barrier}.withValues(alpha: {opacity}),
  shape: RoundedRectangleBorder(
    borderRadius: BorderRadius.vertical(top: Radius.circular({sheet_radius})),
  ),
);
"""


def gen_app_bar_theme(spec):
    a = (spec.get("components") or {}).get("appBar") or {}
    title = a.get("titleStyle", "titleLarge")
    fg = color_ref(a.get("foreground", "onSurface"))
    return f"""{HEADER}
import 'package:flutter/material.dart';

import '../tokens/app_colors.dart';
import '../tokens/app_typography.dart';

AppBarTheme appBarTheme(ColorScheme colors, AppColorExtension appColors) =>
    AppBarTheme(
      backgroundColor: {color_ref(a.get('background', 'surface'))},
      foregroundColor: {fg},
      elevation: {num(a.get('elevation', 0))},
      scrolledUnderElevation: 0,
      centerTitle: {'true' if a.get('centerTitle') else 'false'},
      titleTextStyle: AppTypography.{title}.copyWith(color: {fg}),
    );
"""


def gen_app_theme():
    return f"""{HEADER}
import 'package:flutter/material.dart';

import 'component_themes/app_bar_theme.dart';
import 'component_themes/button_themes.dart';
import 'component_themes/color_schemes.dart';
import 'component_themes/input_decoration_theme.dart';
import 'component_themes/surface_themes.dart';
import 'tokens/app_colors.dart';
import 'tokens/app_text_extension.dart';
import 'tokens/app_typography.dart';

abstract final class AppTheme {{
  static ThemeData get light =>
      _build(lightColorScheme, AppColorExtension.light);

  static ThemeData get dark => _build(darkColorScheme, AppColorExtension.dark);

  static ThemeData _build(ColorScheme colors, AppColorExtension appColors) =>
      ThemeData(
        useMaterial3: true,
        colorScheme: colors,
        scaffoldBackgroundColor: colors.surface,
        fontFamily: AppTypography.fontFamily,
        fontFamilyFallback: AppTypography.fontFamilyFallback,
        textTheme: AppTypography.textTheme.apply(
          bodyColor: colors.onSurface,
          displayColor: colors.onSurface,
        ),
        appBarTheme: appBarTheme(colors, appColors),
        filledButtonTheme: filledButtonTheme(colors, appColors),
        outlinedButtonTheme: outlinedButtonTheme(colors, appColors),
        textButtonTheme: textButtonTheme(colors, appColors),
        inputDecorationTheme: inputDecorationTheme(colors, appColors),
        cardTheme: cardTheme(colors, appColors),
        chipTheme: chipTheme(colors, appColors),
        dividerTheme: dividerTheme(colors, appColors),
        bottomSheetTheme: bottomSheetTheme(colors, appColors),
        extensions: [appColors, AppTextExtension.withColor(colors.onSurface)],
      );
}}
"""


def gen_context_ext():
    return f"""{HEADER}
import 'package:flutter/material.dart';

import 'tokens/app_colors.dart';
import 'tokens/app_text_extension.dart';

/// The only way widgets read theme values:
///   context.colors.primary        (Material ColorScheme roles)
///   context.appColors.success     (brand roles Material lacks)
///   context.textTheme.titleLarge  (Material text roles)
///   context.appText.numericMetric (extra text styles from the design system)
extension ThemeContextExt on BuildContext {{
  ThemeData get theme => Theme.of(this);

  ColorScheme get colors => theme.colorScheme;

  TextTheme get textTheme => theme.textTheme;

  AppColorExtension get appColors =>
      theme.extension<AppColorExtension>() ?? AppColorExtension.light;

  AppTextExtension get appText =>
      theme.extension<AppTextExtension>() ??
      AppTextExtension.withColor(colors.onSurface);
}}
"""


def gen_barrel(pkg):
    return f"""{HEADER}
/// Import this barrel from widgets: `import 'package:{pkg}/shared/theme/theme.dart';`
library;

export 'app_theme.dart';
export 'theme_context_ext.dart';
export 'tokens/app_colors.dart' show AppColorExtension;
export 'tokens/app_dimensions.dart';
export 'tokens/app_text_extension.dart';
export 'tokens/app_typography.dart';
"""


# ---------------------------------------------------------------- preview + tests


def gen_preview(spec, pkg):
    ext = list(ts.extension_colors(spec).keys())
    extras = list(((spec.get("typography") or {}).get("extras") or {}).keys())
    roles = "\n".join(f"        ('{r}', c.{r})," for r in ts.COLOR_ROLES)
    ext_rows = "\n".join(f"        ('{n}', a.{n})," for n in ext)
    type_rows = "\n".join(f"        ('{r}', t.{r})," for r in ts.TYPE_ROLES)
    extra_rows = "\n".join(f"        ('{n}', x.{n})," for n in extras)
    extras_var = "\n    final x = context.appText;" if extras else ""
    return f"""{HEADER}
import 'package:flutter/material.dart';
import 'package:{pkg}/shared/theme/theme.dart';

/// Debug-only preview of every theme token and themed component, for checking
/// a generated theme against the design system in light and dark mode.
/// Not localized on purpose — it's a developer/designer tool, not app UI.
/// Open it temporarily, e.g. `home: const ThemePreviewScreen()` in a debug build.
class ThemePreviewScreen extends StatelessWidget {{
  const ThemePreviewScreen({{super.key}});

  @override
  Widget build(BuildContext context) {{
    final c = context.colors;
    final a = context.appColors;
    final t = context.textTheme;{extras_var}
    return Scaffold(
      appBar: AppBar(title: const Text('Theme preview')),
      body: ListView(
        padding: const EdgeInsets.all(AppDimensions.screenPadding),
        children: [
          const _Heading('Color roles'),
          for (final (name, color) in [
{roles}
          ])
            _Swatch(name: name, color: color),
          const _Heading('Brand colors (context.appColors)'),
          for (final (name, color) in [
{ext_rows}
          ])
            _Swatch(name: name, color: color),
          const _Heading('Text roles (context.textTheme)'),
          for (final (name, style) in [
{type_rows}
          ])
            Text(name, style: style),
          const _Heading('Extra text styles (context.appText)'),
          for (final (name, style) in <(String, TextStyle?)>[
{extra_rows}
          ])
            Text(name, style: style),
          const _Heading('Components'),
          FilledButton(onPressed: () {{}}, child: const Text('Filled button')),
          const SizedBox(height: AppDimensions.spacingSm),
          const FilledButton(onPressed: null, child: Text('Disabled')),
          const SizedBox(height: AppDimensions.spacingSm),
          OutlinedButton(onPressed: () {{}}, child: const Text('Outlined button')),
          TextButton(onPressed: () {{}}, child: const Text('Text button')),
          const SizedBox(height: AppDimensions.spacingSm),
          const TextField(decoration: InputDecoration(hintText: 'Input field')),
          const SizedBox(height: AppDimensions.spacingSm),
          const Card(
            child: Padding(
              padding: EdgeInsets.all(AppDimensions.spacingLg),
              child: Text('Card'),
            ),
          ),
          const Wrap(children: [Chip(label: Text('Chip'))]),
          const Divider(),
        ],
      ),
    );
  }}
}}

class _Heading extends StatelessWidget {{
  const _Heading(this.text);

  final String text;

  @override
  Widget build(BuildContext context) => Padding(
    padding: const EdgeInsets.only(
      top: AppDimensions.spacingXl,
      bottom: AppDimensions.spacingSm,
    ),
    child: Text(text, style: context.textTheme.titleMedium),
  );
}}

class _Swatch extends StatelessWidget {{
  const _Swatch({{required this.name, required this.color}});

  final String name;
  final Color color;

  @override
  Widget build(BuildContext context) {{
    final hex = color.toARGB32().toRadixString(16).padLeft(8, '0').toUpperCase();
    final onColor = ThemeData.estimateBrightnessForColor(color) == Brightness.dark
        ? Colors.white
        : Colors.black;
    return Container(
      color: color,
      padding: const EdgeInsets.all(AppDimensions.spacingSm),
      child: Text('$name  #$hex', style: TextStyle(color: onColor)),
    );
  }}
}}
"""


def gen_tests(spec, pkg):
    ext = ts.extension_colors(spec)
    ext_names = list(ext.keys())
    extras = list(((spec.get("typography") or {}).get("extras") or {}).keys())
    first = ext_names[0]
    boundary = ts.component_boundary_pairs(spec)
    pair_roles = sorted({r for bg, fg, _ in ts.CONTRAST_PAIRS for r in (bg, fg)} |
                        {r for _, bg, fg in boundary for r in (bg, fg) if not r.startswith("ext.")})
    role_map = "\n".join(f"  '{r}': c.{r}," for r in pair_roles)
    ext_map = "\n".join(f"  'ext.{n}': a.{n}," for n in ext_names)
    pairs = [(bg, fg, m) for bg, fg, m in ts.CONTRAST_PAIRS]
    for n, e in ext.items():
        m = ts.EXTENSION_USAGE_MIN.get(e.get("usage", "text"))
        if m:
            pairs.append(("surface", f"ext.{n}", m))
    for pair_id, bg, fg in boundary:
        pairs.append((bg, fg, 3.0, pair_id))
    pair_lines = "\n".join(
        f"  ('{p[3] if len(p) > 3 else p[0] + '/' + p[1]}', '{p[0]}', '{p[1]}', {p[2]}),"
        for p in pairs)
    accepted = []
    for exc in spec.get("acceptedContrastExceptions") or []:
        modes = ["light", "dark"] if exc.get("mode") == "both" else [exc.get("mode")]
        accepted += [f"  '{m}:{exc['pair']}',  // {exc.get('reason', '')}" for m in modes]
    accepted_lines = "\n".join(accepted)
    text_test = ""
    if extras:
        e0 = extras[0]
        text_test = f"""
    test('AppTextExtension copyWith and lerp', () {{
      final light = AppTextExtension.withColor(const Color(0xFF000000));
      final dark = AppTextExtension.withColor(const Color(0xFFFFFFFF));

      expect(light.copyWith().{e0}, light.{e0});
      expect(light.lerp(dark, 1).{e0}.color, dark.{e0}.color);
      expect(light.lerp(null, 0.5), same(light));
    }});
"""
    else:
        text_test = """
    test('AppTextExtension is empty but usable', () {
      const ext = AppTextExtension();
      expect(ext.copyWith(), same(ext));
      expect(ext.lerp(null, 0.5), same(ext));
    });
"""

    app_theme_test = f"""{HEADER}
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:{pkg}/shared/theme/theme.dart';

import '../../helpers/pump_app.dart';

void main() {{
  group('AppTheme', () {{
    test('light and dark themes carry both extensions', () {{
      expect(AppTheme.light.brightness, Brightness.light);
      expect(AppTheme.dark.brightness, Brightness.dark);
      for (final theme in [AppTheme.light, AppTheme.dark]) {{
        expect(theme.extension<AppColorExtension>(), isNotNull);
        expect(theme.extension<AppTextExtension>(), isNotNull);
      }}
    }});

    test('AppColorExtension copyWith and lerp', () {{
      final light = AppColorExtension.light;
      final dark = AppColorExtension.dark;

      expect(light.copyWith({first}: dark.{first}).{first}, dark.{first});
      expect(light.copyWith().{first}, light.{first});
      expect(light.lerp(dark, 1).{first}, dark.{first});
      expect(light.lerp(null, 0.5), same(light));
    }});
{text_test}
    testWidgets('context extensions read from the active theme', (
      tester,
    ) async {{
      late BuildContext captured;
      await tester.pumpApp(
        Builder(
          builder: (context) {{
            captured = context;
            return const SizedBox();
          }},
        ),
        theme: AppTheme.dark,
      );

      expect(captured.colors.brightness, Brightness.dark);
      expect(captured.appColors.{first}, AppColorExtension.dark.{first});
      expect(captured.appText, isNotNull);
      expect(captured.textTheme.bodyMedium, isNotNull);
    }});
  }});
}}
"""

    contrast_test = f"""{HEADER}
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:{pkg}/shared/theme/theme.dart';

// WCAG 2 contrast for every foreground/background pair, on the FINAL themes —
// including colours Flutter derives from the seed (dark mode, unprovided roles).
// A pair may only be below its minimum if the spec's
// acceptedContrastExceptions lists it with a reason.

const _pairs = <(String, String, String, double)>[
{pair_lines}
];

const _accepted = <String>{{
{accepted_lines}
}};

double _ratio(Color a, Color b) {{
  final la = a.computeLuminance();
  final lb = b.computeLuminance();
  return (math.max(la, lb) + 0.05) / (math.min(la, lb) + 0.05);
}}

Map<String, Color> _colors(ThemeData theme) {{
  final c = theme.colorScheme;
  final a = theme.extension<AppColorExtension>()!;
  return {{
{role_map}
{ext_map}
  }};
}}

void main() {{
  for (final (mode, theme) in [('light', AppTheme.light), ('dark', AppTheme.dark)]) {{
    group('contrast ($mode)', () {{
      final colors = _colors(theme);
      for (final (pair, bg, fg, min) in _pairs) {{
        final id = '$mode:$pair';
        test('$pair ≥ $min:1', () {{
          final ratio = _ratio(colors[bg]!, colors[fg]!);
          if (_accepted.contains(id)) return;
          expect(
            ratio,
            greaterThanOrEqualTo(min),
            reason: '$id is ${{ratio.toStringAsFixed(2)}}:1',
          );
        }});
      }}
    }});
  }}
}}
"""

    preview_test = f"""{HEADER}
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:{pkg}/shared/theme/preview/theme_preview_screen.dart';
import 'package:{pkg}/shared/theme/theme.dart';

import '../../helpers/pump_app.dart';

void main() {{
  group('ThemePreviewScreen', () {{
    for (final (mode, theme) in [('light', AppTheme.light), ('dark', AppTheme.dark)]) {{
      testWidgets('renders every token in $mode mode', (tester) async {{
        await tester.pumpApp(const ThemePreviewScreen(), theme: theme);
        // The page's own list: text fields in the preview have inner scrollables too.
        await tester.scrollUntilVisible(find.text('Card'), 400, scrollable: find.byType(Scrollable).first);

        expect(tester.takeException(), isNull);
      }});
    }}
  }});
}}
"""
    return app_theme_test, contrast_test, preview_test


# ---------------------------------------------------------------- report


def gen_report(spec, dims, provenance, provisional, warnings, font_warning):
    light, dark = ts.mode_colors(spec, "light"), ts.mode_colors(spec, "dark")
    ext = ts.extension_colors(spec)
    typo = spec.get("typography") or {}
    roles, extras = typo.get("roles") or {}, typo.get("extras") or {}
    out = [f"# Theme report — {spec['name']}", ""]
    out.append(f"Generated {datetime.date.today().isoformat()} from `design/theme.spec.json` by the "
               "flutter-design-system-theme skill. Regenerate after every spec change.")
    out.append("")
    if provisional:
        out += ["> **PROVISIONAL** — some conflicts are unresolved and use the recommended value. "
                "Confirm them below, mark them resolved in the spec and regenerate.", ""]
    sources = spec.get("sources") or []
    if sources:
        out.append("**Sources:** " + "; ".join(f"`{s.get('file', s.get('id'))}` ({s.get('type')})" for s in sources))
        out.append("")

    conflicts = spec.get("conflicts") or []
    out += ["## Conflicts", ""]
    if conflicts:
        out += ["| Target | Candidates | Used | Status |", "|---|---|---|---|"]
        for c in conflicts:
            cands = "<br>".join(f"`{x.get('value')}` ← {x.get('source')}" for x in c.get("candidates", []))
            used = c.get("resolution", c.get("recommendation"))
            status = "resolved" if c.get("status") == "resolved" else f"**open** — {c.get('reason', '')}"
            out.append(f"| `{c['target']}` | {cands} | `{used}` | {status} |")
    else:
        out.append("None.")
    out.append("")

    out += ["## Colour roles", "", "| Role | Light | Dark |", "|---|---|---|"]
    for role in ts.COLOR_ROLES:
        lv = f"`{light[role]['value']}` ← {light[role].get('source', '')}" if role in light else "derived from seed"
        dv = f"`{dark[role]['value']}` ← {dark[role].get('source', '')}" if role in dark else "derived from seed"
        out.append(f"| `{role}` | {lv} | {dv} |")
    seed = spec.get("seed")
    out += ["", f"Seed: `{(seed or light['primary'])['value']}`, scheme variant "
                f"`{(spec.get('policy') or {}).get('schemeVariant', 'fidelity')}`.", ""]

    out += ["## Brand colours (`context.appColors`)", "", "| Name | Usage | Light | Dark |", "|---|---|---|---|"]
    for name, e in ext.items():
        how = {"border": "outline tone", "fill": "container tone"}.get(e.get("usage", "text"), "foreground tone")
        dv = f"`{e['dark']['value']}` ← {e['dark'].get('source', '')}" if e.get("dark") else f"derived (tonal, {how})"
        out.append(f"| `{name}` | {e.get('usage', 'text')} | `{e['light']['value']}` ← {e['light'].get('source', '')} | {dv} |")
    out.append("")

    family = (typo.get("fontFamily") or {}).get("value") or "platform default"
    fallback = ", ".join(typo.get("fontFamilyFallback") or []) or "—"
    out += ["## Typography", "", f"Font: **{family}**, fallback: {fallback}.", ""]
    if font_warning:
        out += [f"> ⚠️ {font_warning}", ""]
    out += ["| Role | Size / line | Weight | Tracking | From |", "|---|---|---|---|---|"]
    for role in ts.TYPE_ROLES:
        if role in roles:
            s = roles[role]
            out.append(f"| `{role}` | {num(s['fontSize'])} / {num(s.get('lineHeight', '-'))} | {s.get('fontWeight', 400)} "
                       f"| {num(s.get('letterSpacing', 0))} | `{s.get('token', role)}` ← {s.get('source', '')} |")
        else:
            size, line, weight, ls = ts.MATERIAL_TYPE_SCALE[role]
            out.append(f"| `{role}` | {size} / {line} | {weight} | {ls} | Material 3 default |")
    for name, s in extras.items():
        feats = f" features: {', '.join(s['fontFeatures'])}" if s.get("fontFeatures") else ""
        out.append(f"| `appText.{name}` | {num(s['fontSize'])} / {num(s.get('lineHeight', '-'))} | {s.get('fontWeight', 400)} "
                   f"| {num(s.get('letterSpacing', 0))} | `{s.get('token', name)}` ← {s.get('source', '')}{feats} |")
    out.append("")

    out += ["## Dimensions (`AppDimensions`)", "", "| Name | dp | From |", "|---|---|---|"]
    for group in ("spacing", "radius", "sizes"):
        for key, value in dims[group].items():
            out.append(f"| `{key}` | {num(value)} | {provenance[key]} |")
    out.append("")

    comps = spec.get("components") or {}
    out += ["## Components", ""]
    if comps:
        for name, props in comps.items():
            shown = ", ".join(f"{k}: `{v}`" for k, v in props.items() if k not in ("source", "note"))
            out.append(f"- **{name}** — {shown}" + (f" ← {props['source']}" if props.get("source") else "")
                       + (f"  \n  _Note: {props['note']}_" if props.get("note") else ""))
    else:
        out.append("None specified; shell defaults used.")
    out.append("")

    out += ["## Contrast (provided colours)", "",
            "Derived colours are checked by `test/shared/theme/theme_contrast_test.dart`.", "",
            "| Mode | Pair | Ratio | Min | Result |", "|---|---|---|---|---|"]
    for r in ts.contrast_results(spec):
        result = {"pass": "✅", "fail": "❌", "accepted": f"accepted — {r['reason']}"}[r["status"]]
        out.append(f"| {r['mode']} | `{r['pair']}` | {r['ratio']:.2f} | {r['min']} | {result} |")
    out.append("")

    unmapped = spec.get("unmapped") or []
    out += ["## Not mapped", ""]
    out += [f"- `{u.get('token')}` `{u.get('value', '')}` — {u.get('reason', '')}" for u in unmapped] or ["Nothing."]
    out.append("")
    notes = spec.get("notes") or []
    if notes:
        out += ["## Notes", ""] + [f"- {n}" for n in notes] + [""]
    if warnings:
        out += ["## Validator warnings", ""] + [f"- {w}" for w in warnings] + [""]
    return "\n".join(out)


# ---------------------------------------------------------------- main


def font_declared(root, family):
    pubspec = (root / "pubspec.yaml").read_text()
    return bool(re.search(rf"family:\s*['\"]?{re.escape(family)}['\"]?\s*$", pubspec, re.M)) or "google_fonts:" in pubspec


def format_files(root, rels):
    uses_fvm = any((d / n).exists() for d in (root, root.parent) for n in (".fvmrc", ".fvm"))
    cmd = (["fvm", "dart"] if uses_fvm and shutil.which("fvm") else ["dart"]) + ["format", *rels]
    if shutil.which(cmd[0]):
        subprocess.run(cmd, cwd=root, capture_output=True, text=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="Flutter app root (a flutter-app-structure project)")
    ap.add_argument("--spec", default="design/theme.spec.json", help="Spec path, relative to --root")
    ap.add_argument("--allow-open-conflicts", action="store_true",
                    help="Generate a PROVISIONAL theme using each open conflict's current value")
    ap.add_argument("--dry-run", action="store_true", help="List the files that would be written")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not (root / "lib/shared/theme/theme.dart").exists():
        sys.exit("lib/shared/theme/theme.dart not found — this generator targets apps built with the "
                 "flutter-app-structure skill. Bootstrap or migrate the app first.")
    try:
        spec = ts.load_spec(root / args.spec)
    except ts.SpecError as e:
        sys.exit(f"error: {e}")

    errors, warnings = ts.validate(spec, allow_open_conflicts=args.allow_open_conflicts)
    if errors:
        for e in errors:
            print(f"error: {e}")
        sys.exit(f"\n{len(errors)} error(s) — fix the spec (run validate_theme_spec.py for details).")
    provisional = any(c.get("status", "open") == "open" for c in spec.get("conflicts") or [])

    pkg = read_package(root)
    dims, provenance = resolve_dims(spec)
    palette = Palette()
    typo = spec.get("typography") or {}
    families = [f for f in [(typo.get("fontFamily") or {}).get("value"), *(typo.get("fontFamilyFallback") or [])] if f]
    missing = [f for f in families if not font_declared(root, f)]
    font_warning = None
    if missing:
        font_warning = (f"Font(s) not declared in pubspec.yaml: {', '.join(missing)} (no `family:` entry and no google_fonts). "
                        "Add the font files under assets/fonts/ and declare them — ask the user for the files or whether to "
                        "use google_fonts — otherwise text falls back to the platform font.")

    colors_dart = gen_colors(spec, palette)
    app_theme_test, contrast_test, preview_test = gen_tests(spec, pkg)
    files = {
        "lib/shared/theme/tokens/app_colors.dart": colors_dart,
        "lib/shared/theme/tokens/app_typography.dart": gen_typography(spec),
        "lib/shared/theme/tokens/app_text_extension.dart": gen_text_extension(spec),
        "lib/shared/theme/tokens/app_dimensions.dart": gen_dimensions(dims, provenance),
        "lib/shared/theme/component_themes/color_schemes.dart": gen_color_schemes(spec),
        "lib/shared/theme/component_themes/button_themes.dart": gen_button_themes(spec, dims),
        "lib/shared/theme/component_themes/input_decoration_theme.dart": gen_input_theme(spec, dims),
        "lib/shared/theme/component_themes/surface_themes.dart": gen_surface_themes(spec, dims),
        "lib/shared/theme/component_themes/app_bar_theme.dart": gen_app_bar_theme(spec),
        "lib/shared/theme/app_theme.dart": gen_app_theme(),
        "lib/shared/theme/theme_context_ext.dart": gen_context_ext(),
        "lib/shared/theme/theme.dart": gen_barrel(pkg),
        "lib/shared/theme/preview/theme_preview_screen.dart": gen_preview(spec, pkg),
        "test/shared/theme/app_theme_test.dart": app_theme_test,
        "test/shared/theme/theme_contrast_test.dart": contrast_test,
        "test/shared/theme/theme_preview_screen_test.dart": preview_test,
        "design/THEME_REPORT.md": gen_report(spec, dims, provenance, provisional, warnings, font_warning),
    }
    files = {rel: prune_token_imports(text) if rel.startswith("lib/shared/theme/component_themes/") else text
             for rel, text in files.items()}

    for rel, content in files.items():
        path = root / rel
        existed = path.exists()
        hand_written = existed and "GENERATED by the flutter-design-system-theme" not in path.read_text()
        label = "replace hand-written" if hand_written else ("update" if existed else "create")
        print(f"{'would ' if args.dry_run else ''}{label}: {rel}")
        if not args.dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if not args.dry_run:
        format_files(root, [r for r in files if r.endswith(".dart")])

    for w in warnings:
        print(f"warning: {w}")
    if font_warning:
        print(f"warning: {font_warning}")
    print("\nPROVISIONAL theme (open conflicts) — confirm them, mark resolved, regenerate." if provisional else
          "\nTheme generated.")
    print("Next: run `flutter analyze` and `flutter test` (prefix with fvm if used), open design/THEME_REPORT.md,\n"
          "and review ThemePreviewScreen in light and dark mode.")


if __name__ == "__main__":
    main()
